//! Parser corpus sweep task
//!
//! Scans system-installed Perl `.pm` files, parses each with the v3 recursive
//! descent parser, and reports clean-parse rates plus error buckets.
//!
//! Produces a JSON report suitable for baseline comparison and regression gating.

use color_eyre::eyre::{Context, Result};
use indicatif::{ProgressBar, ProgressStyle};
#[cfg(test)]
use perl_parser::{Node, NodeKind};
use perl_parser::{ParseError, Parser, RecoverySalvageClass, RecoverySalvageProfile};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::io::BufRead;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use std::time::Instant;
use walkdir::WalkDir;

// ---------------------------------------------------------------------------
// Lazy-compiled regexes for error normalization
// ---------------------------------------------------------------------------

static RE_SYNTAX_POS: LazyLock<Option<Regex>> =
    LazyLock::new(|| Regex::new(r"^Invalid syntax at position \d+: (.+)$").ok());
static RE_TRAILING_AT: LazyLock<Option<Regex>> = LazyLock::new(|| Regex::new(r" at \d+$").ok());

// ---------------------------------------------------------------------------
// Semantic bucket mapping table (first match wins)
// ---------------------------------------------------------------------------

const SEMANTIC_BUCKETS: &[(&str, &str)] = &[
    // NOTE: "catastrophic_backtracking" bucket removed (#2029): the parser emits
    // "Nested quantifiers detected (possible backtracking risk)" via record_error()
    // as a non-fatal diagnostic — it never produces a NodeKind::Error node, so it
    // cannot appear in the sweep's first_error_buckets counter. No replacement needed.
    //
    // NOTE: "expected_import_item" bucket removed (#2029): the substring
    // "Expected string or identifier in import" is not generated by any code in
    // crates/. The import-list parser does not produce this error message.
    ("Expected variable, found", "expected_variable"),
    ("Expected comma or closing parenthesis in signature", "signature_param"),
    ("Expected comma or closing parenthesis", "expected_comma_or_close_paren"),
    ("Expected module name or version", "expected_module_name"),
    ("Expected '>' to close angle", "unclosed_angle"),
    ("Substitution operator should be", "substitution_misparse"),
    ("Missing closing delimiter in substitution", "unclosed_substitution_delimiter"),
    ("Invalid substitution modifier", "invalid_substitution_modifier"),
    // Expression errors — user-friendly token names ('=>', '->', etc.)
    ("expected expression, found '=>'", "unexpected_fat_arrow_expr"),
    ("expected expression, found '->'", "unexpected_arrow_expr"),
    ("expected expression, found '/'", "unexpected_slash_expr"),
    ("expected expression, found '?'", "unexpected_question_expr"),
    ("expected expression, found 'return'", "unexpected_return_expr"),
    // Expression errors — keyword tokens (subcategories of catch-all, must precede it)
    ("expected expression, found 'unless'", "unexpected_token_unless"),
    ("expected expression, found 'until'", "unexpected_token_until"),
    ("expected expression, found 'while'", "unexpected_token_while"),
    ("expected expression, found 'else'", "unexpected_token_else"),
    ("expected expression, found 'elsif'", "unexpected_token_elsif"),
    ("expected expression, found 'for'", "unexpected_token_for"),
    ("expected expression, found 'foreach'", "unexpected_token_foreach"),
    ("expected expression, found 'use'", "unexpected_token_use"),
    ("expected expression, found 'no'", "unexpected_token_no"),
    // Expression errors — word operators
    ("expected expression, found 'or'", "unexpected_word_op_or"),
    ("expected expression, found 'and'", "unexpected_word_op_and"),
    ("expected expression, found 'not'", "unexpected_word_op_not"),
    ("expected expression, found 'xor'", "unexpected_word_op_xor"),
    // Expression errors — punctuation
    ("expected expression, found ','", "unexpected_comma_expr"),
    ("expected expression, found ';'", "unexpected_semicolon_expr"),
    ("expected expression, found '}'", "unexpected_rbrace_expr"),
    ("expected expression, found ')'", "unexpected_rparen_expr"),
    ("expected expression, found end of input", "unexpected_eof_expr"),
    // Expression errors — closing bracket
    ("expected expression, found ']'", "unexpected_rbracket_expr"),
    // Expression errors — keywords not yet explicitly bucketed
    ("expected expression, found 'if'", "unexpected_token_if"),
    ("expected expression, found 'my'", "unexpected_token_my"),
    ("expected expression, found 'our'", "unexpected_token_our"),
    ("expected expression, found 'local'", "unexpected_token_local"),
    ("expected expression, found 'sub'", "unexpected_token_sub"),
    ("expected expression, found 'package'", "unexpected_token_package"),
    ("expected expression, found 'eval'", "unexpected_token_eval"),
    ("expected expression, found 'do'", "unexpected_token_do"),
    ("expected expression, found 'next'", "unexpected_token_next"),
    ("expected expression, found 'last'", "unexpected_token_last"),
    ("expected expression, found 'redo'", "unexpected_token_redo"),
    // Expression errors — assignment operators ('==' before '=' is defensive: without quotes
    // "found ==" would contain "found =" as a substring, so the ordering is correct even
    // though the quoted forms are distinct strings in practice)
    ("expected expression, found '=='", "unexpected_eq_expr"),
    ("expected expression, found '=~'", "unexpected_match_expr"),
    ("expected expression, found '='", "unexpected_assign_expr"),
    // Expression errors — range operator
    ("expected expression, found '..'", "unexpected_range_expr"),
    // Catch-all for remaining unexpected expression tokens (MUST remain last)
    ("expected expression, found", "unexpected_token_in_expr"),
    // Unclosed delimiters — user-friendly names ('}', ')', ']')
    ("expected '}', found ';'", "unclosed_brace_semicolon"),
    ("expected '}', found end of input", "unclosed_brace_eof"),
    ("expected '}'", "unclosed_brace"),
    ("expected ')', found identifier", "unclosed_paren_identifier"),
    ("expected ')'", "unclosed_paren"),
    ("expected ']'", "unclosed_bracket"),
    ("expected '('", "expected_left_paren"),
    ("expected '{'", "expected_left_brace"),
    ("expected ';'", "expected_semicolon"),
    ("expected ':'", "expected_colon"),
    ("expected identifier", "expected_identifier"),
    ("expected ','", "expected_comma"),
];

/// Configuration for the corpus sweep
#[derive(Debug, Clone)]
pub struct SweepConfig {
    /// Optional corpus profile override for report and receipt naming.
    pub corpus_profile: Option<String>,
    /// High-level roots for report metadata (e.g., `/usr/share/perl`)
    pub base_roots: Vec<PathBuf>,
    /// Expanded directories to actually scan (includes versioned subdirs)
    pub corpus_roots: Vec<PathBuf>,
    /// Optional manifest file listing module names to resolve via `perl`
    pub manifest_path: Option<PathBuf>,
    /// Extra library roots exposed via PERL5LIB while resolving manifest modules
    pub manifest_perl5lib: Vec<PathBuf>,
    /// Optional JSON output file
    pub output_path: Option<PathBuf>,
    /// Compare against baseline JSON file
    pub baseline_path: Option<PathBuf>,
    /// Return nonzero if regression detected
    pub enforce: bool,
    /// Include per-file details in output
    pub verbose: bool,
    /// Write receipt JSON to target/receipts/<profile>-corpus-sweep.json
    pub receipt: bool,
}

/// Overall sweep report (serialized to JSON)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SweepReport {
    pub schema_version: String,
    pub commit: String,
    pub timestamp: String,
    /// Corpus profile identifier (for example "system", "common", or "cpan")
    #[serde(default = "default_corpus_profile")]
    pub corpus_profile: String,
    /// High-level base roots (e.g., 3 base directories)
    pub corpus_roots: Vec<String>,
    /// Number of actual directories scanned after expansion
    #[serde(default)]
    pub resolved_roots_count: usize,
    /// Perl version from `perl -e 'print $]'`
    #[serde(default = "default_perl_version")]
    pub perl_version: String,
    pub total_files: usize,
    pub files_unreadable: usize,
    pub clean_files: usize,
    pub files_with_errors: usize,
    #[serde(default)]
    pub total_dirty_files: usize,
    #[serde(default)]
    pub files_with_structured_recovery_only: usize,
    #[serde(default)]
    pub files_with_error_nodes: usize,
    #[serde(default)]
    pub files_with_catastrophic_parse_failure: usize,
    pub total_error_nodes: usize,
    #[serde(default)]
    pub recovered_node_count: usize,
    #[serde(default)]
    pub first_unrecovered_error_node_buckets: BTreeMap<String, usize>,
    pub first_error_buckets: BTreeMap<String, usize>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty", default)]
    pub files_by_bucket: BTreeMap<String, Vec<String>>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub file_results: Vec<FileResult>,
    pub elapsed_secs: f64,
    /// Phase-timing breakdown of the sweep (discovery / IO / parse / total).
    ///
    /// Introduced in schema 1.3.0. Absent in older receipts; deserializes as None.
    /// See `PhaseTimings` for the semantics of each field.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub phase_timings: Option<PhaseTimings>,
    /// Median error-node density across dirty files, in errors per 1k LOC.
    ///
    /// Introduced in schema 1.3.0. `None` when no dirty files have a recorded
    /// line count (older verbose=false receipts, or empty corpora).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub median_error_density_per_1k_loc: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub recovery_salvage_rate: Option<f64>,
    /// Top slowest files by parse duration (always captured, regardless of verbose mode).
    ///
    /// Introduced in schema 1.3.0. Always present when phase timings are
    /// present; empty when no per-file timings were recorded.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub slowest_files: Vec<SlowestFileEntry>,
}

/// Phase-timing breakdown of a corpus sweep in milliseconds.
///
/// Fields:
/// - `discovery_ms`: time spent walking the corpus / resolving the manifest.
/// - `file_io_ms`: cumulative wall time spent reading file contents from disk.
/// - `parse_ms`: cumulative wall time spent inside `Parser::parse()`
///   (lex + parse combined; lex-only separation is a future extension —
///   tracked by #4063 as a TODO pending `perl-lexer` instrumentation).
/// - `total_ms`: total wall time of the sweep from start to report assembly.
///
/// Times are wall-clock milliseconds; `file_io_ms + parse_ms` can exceed
/// `total_ms - discovery_ms` if the sweep is ever parallelized (currently
/// it is not), but equals it under the current sequential implementation.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct PhaseTimings {
    pub discovery_ms: u64,
    pub file_io_ms: u64,
    pub parse_ms: u64,
    pub total_ms: u64,
}

/// Compact slowest-file entry suitable for the receipt and for later analysis.
///
/// Does not duplicate the full `FileResult`; captures just what is needed
/// for a top-N latency report so that receipts stay small even with tens of
/// thousands of files.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SlowestFileEntry {
    pub path: String,
    pub parse_duration_ms: u64,
    pub line_count: usize,
}

fn default_corpus_profile() -> String {
    "system".to_string()
}

fn receipt_path_for_profile(profile: &str) -> PathBuf {
    PathBuf::from(format!("target/receipts/{profile}-corpus-sweep.json"))
}

fn default_perl_version() -> String {
    "unknown".to_string()
}

fn portable_report_path(path: &Path) -> String {
    match path.strip_prefix(super::cpan_corpus::workspace_root()) {
        Ok(relative) => relative.display().to_string(),
        Err(_) => path.display().to_string(),
    }
}

/// Per-file result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileResult {
    pub path: String,
    pub status: String,
    pub error_node_count: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub recovered_count: Option<usize>,
    /// Wall time spent parsing this file, in milliseconds.
    ///
    /// Introduced in schema 1.3.0. Absent for `status == "unreadable"`
    /// (no parse attempted) and for receipts predating the schema bump.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub parse_duration_ms: Option<u64>,
    /// Number of lines in the source file (counted from file contents).
    ///
    /// Introduced in schema 1.3.0. Absent for `status == "unreadable"` and
    /// for receipts predating the schema bump.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub line_count: Option<usize>,
}

/// A single ratchet violation
#[derive(Debug, Clone)]
pub struct RatchetViolation {
    pub metric: String,
    pub baseline_value: String,
    pub current_value: String,
}

/// Default high-level corpus root directories for system Perl
pub fn default_base_roots() -> Vec<PathBuf> {
    vec![
        PathBuf::from("/usr/share/perl"),
        PathBuf::from("/usr/lib/x86_64-linux-gnu/perl"),
        PathBuf::from("/usr/share/perl5"),
    ]
}

/// Expand base roots into all scannable directories (including versioned subdirs)
pub fn resolve_corpus_roots(base_roots: &[PathBuf]) -> Vec<PathBuf> {
    let mut roots = Vec::new();
    for base in base_roots {
        if base.exists() {
            roots.push(base.clone());
        }
        // Expand versioned subdirectories like /usr/share/perl/5.38
        if let Ok(entries) = fs::read_dir(base) {
            for entry in entries.flatten() {
                let p = entry.path();
                if p.is_dir() {
                    roots.push(p);
                }
            }
        }
    }
    if roots.is_empty() { base_roots.to_vec() } else { roots }
}

/// Get the Perl version from the system `perl` binary
fn get_perl_version() -> String {
    std::process::Command::new("perl")
        .args(["-e", "print $]"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

/// Summary of Error nodes found in an AST.
#[cfg(test)]
struct ErrorSummary {
    /// Total count of NodeKind::Error nodes in the tree
    count: usize,
    /// The message from the Error node with the smallest location.start
    first_message: Option<String>,
}

/// Walk the AST and summarize error nodes.
///
/// Counts all `NodeKind::Error` nodes and captures the raw message from
/// the earliest error by byte offset. Uses `for_each_child` to traverse
/// the full tree including `partial` subtrees of Error nodes.
#[cfg(test)]
fn collect_error_summary(root: &Node) -> ErrorSummary {
    let mut count = 0usize;
    let mut first_start = usize::MAX;
    let mut first_message: Option<String> = None;
    walk_errors(root, &mut count, &mut first_start, &mut first_message);
    ErrorSummary { count, first_message }
}

#[cfg(test)]
fn walk_errors(
    node: &Node,
    count: &mut usize,
    first_start: &mut usize,
    first_message: &mut Option<String>,
) {
    if let NodeKind::Error { message, .. } = &node.kind {
        *count += 1;
        if node.location.start < *first_start {
            *first_start = node.location.start;
            *first_message = Some(message.clone());
        }
    }
    node.for_each_child(|child| {
        walk_errors(child, count, first_start, first_message);
    });
}

/// Parse a manifest file into module names (skipping comments and empty lines).
pub fn parse_manifest(manifest_path: &Path) -> Result<Vec<String>> {
    let file = fs::File::open(manifest_path)
        .with_context(|| format!("Failed to open manifest: {}", manifest_path.display()))?;
    let reader = std::io::BufReader::new(file);
    let mut modules = Vec::new();
    for line in reader.lines() {
        let line = line.context("Failed to read manifest line")?;
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        modules.push(trimmed.to_string());
    }
    Ok(modules)
}

/// Resolve module names to file paths via a single `perl` invocation.
///
/// Returns an error if fewer than `min_resolved` modules resolve successfully.
pub fn resolve_manifest_modules(
    manifest_path: &Path,
    perl5lib_paths: &[PathBuf],
    min_resolved: usize,
) -> Result<Vec<PathBuf>> {
    let modules = parse_manifest(manifest_path)?;
    if modules.is_empty() {
        return Err(color_eyre::eyre::eyre!("Manifest is empty: {}", manifest_path.display()));
    }

    let mut resolved = Vec::new();
    let mut unresolved = Vec::new();

    for module in &modules {
        if let Some(path) = resolve_module_in_roots(module, perl5lib_paths) {
            resolved.push(path);
        } else {
            unresolved.push(module.as_str());
        }
    }

    if !unresolved.is_empty() {
        // Fall back to perl require resolution for modules not found directly on disk.
        let module_list = unresolved.join(" ");
        let perl_script = format!(
            r#"for (qw({})) {{ eval "require $_"; (my $f = "$_.pm") =~ s|::|/|g; print "$f=$INC{{$f}}\n" if $INC{{$f}} }}"#,
            module_list
        );

        let mut command = std::process::Command::new("perl");
        if !perl5lib_paths.is_empty() {
            let mut paths = perl5lib_paths.to_vec();
            if let Some(existing) = std::env::var_os("PERL5LIB") {
                paths.extend(std::env::split_paths(&existing));
            }
            let joined = std::env::join_paths(paths)
                .context("Failed to build PERL5LIB for manifest resolution")?;
            command.env("PERL5LIB", joined);
        }
        let output = command
            .args(["-e", &perl_script])
            .output()
            .context("Failed to run perl for module resolution")?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            // Perl may emit warnings for missing modules but still succeed partially
            eprintln!("perl warnings: {stderr}");
        }

        let stdout = String::from_utf8(output.stdout).context("Invalid UTF-8 in perl output")?;
        for line in stdout.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            if let Some((_module_file, path)) = line.split_once('=')
                && let Some(p) = resolve_manifest_module_path(path)
            {
                resolved.push(p);
            }
        }
    }

    resolved.sort();
    resolved.dedup();

    if resolved.len() < min_resolved {
        return Err(color_eyre::eyre::eyre!(
            "Only {} of {} modules resolved (minimum: {}). Resolved: {:?}",
            resolved.len(),
            modules.len(),
            min_resolved,
            resolved,
        ));
    }

    resolved.sort();
    Ok(resolved)
}

fn resolve_module_in_roots(module: &str, roots: &[PathBuf]) -> Option<PathBuf> {
    let relative = PathBuf::from(format!("{}.pm", module.replace("::", "/")));
    roots.iter().map(|root| root.join(&relative)).find(|candidate| candidate.exists())
}

fn resolve_manifest_module_path(path: &str) -> Option<PathBuf> {
    resolve_manifest_module_path_impl(path, windows_manifest_module_path)
}

#[allow(unused_variables)]
fn resolve_manifest_module_path_impl<F>(path: &str, windows_converter: F) -> Option<PathBuf>
where
    F: Fn(&str) -> Option<PathBuf>,
{
    let path = path.trim();
    if path.is_empty() {
        return None;
    }

    let direct = PathBuf::from(path);
    if direct.exists() {
        return Some(direct);
    }

    // Keep the production Windows-only behavior in `windows_manifest_module_path`,
    // but allow tests to inject a converter regardless of host platform.
    if let Some(converted) = windows_converter(path)
        && converted.exists()
    {
        return Some(converted);
    }

    None
}

fn windows_manifest_module_path(path: &str) -> Option<PathBuf> {
    #[cfg(windows)]
    {
        if !path.starts_with('/') {
            return None;
        }

        if let Some(converted) = run_cygpath(Path::new("cygpath"), path) {
            return Some(converted);
        }

        if let Some(cygpath_exe) = git_cygpath_executable() {
            return run_cygpath(cygpath_exe.as_path(), path);
        }
    }

    let _ = path;
    None
}

#[cfg(windows)]
fn run_cygpath(program: &Path, path: &str) -> Option<PathBuf> {
    let output = std::process::Command::new(program).args(["-w", path]).output().ok()?;
    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8(output.stdout).ok()?;
    let converted = stdout.trim();
    if converted.is_empty() {
        return None;
    }

    Some(PathBuf::from(converted))
}

#[cfg(windows)]
fn git_cygpath_executable() -> Option<PathBuf> {
    let output = std::process::Command::new("where.exe").arg("git.exe").output().ok()?;
    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8(output.stdout).ok()?;
    let git_exe = stdout.lines().find(|line| !line.trim().is_empty())?.trim();
    let git_root = PathBuf::from(git_exe).parent()?.parent()?.to_path_buf();
    let cygpath = git_root.join("usr").join("bin").join("cygpath.exe");
    cygpath.exists().then_some(cygpath)
}

/// Enforce strict zero-error policy for common corpus.
///
/// Returns violations if any files are unreadable or contain errors.
pub fn enforce_strict_clean(report: &SweepReport) -> Vec<RatchetViolation> {
    let mut violations = Vec::new();

    if report.files_unreadable > 0 {
        violations.push(RatchetViolation {
            metric: "files_unreadable".to_string(),
            baseline_value: "0".to_string(),
            current_value: report.files_unreadable.to_string(),
        });
    }

    if report.files_with_errors > 0 {
        violations.push(RatchetViolation {
            metric: "files_with_errors".to_string(),
            baseline_value: "0".to_string(),
            current_value: report.files_with_errors.to_string(),
        });
    }

    if report.total_error_nodes > 0 {
        violations.push(RatchetViolation {
            metric: "total_error_nodes".to_string(),
            baseline_value: "0".to_string(),
            current_value: report.total_error_nodes.to_string(),
        });
    }

    violations
}

/// Cap on the size of `SweepReport::slowest_files`.
///
/// Twenty matches pyright's "longest ten files" display at 2x for slightly
/// better coverage, and keeps the receipt small (~1 KB for the slowest list
/// even in the CPAN top-1000 sweep).
const SLOWEST_FILES_LIMIT: usize = 20;

/// Per-file measurement retained in memory during the sweep. Not serialized
/// directly; used to derive `SweepReport::slowest_files` and
/// `SweepReport::median_error_density_per_1k_loc`.
#[derive(Debug, Clone)]
struct FileMeasurement {
    path: String,
    parse_duration_ms: u64,
    line_count: usize,
    error_node_count: usize,
}

/// Select the top `limit` slowest files by parse duration (descending).
///
/// Ties are broken by path for determinism so repeated runs over the same
/// corpus produce identical receipts. Returns an empty vec when
/// `measurements` is empty.
fn top_n_slowest(measurements: &[FileMeasurement], limit: usize) -> Vec<SlowestFileEntry> {
    let mut sorted: Vec<&FileMeasurement> = measurements.iter().collect();
    sorted.sort_by(|a, b| {
        b.parse_duration_ms.cmp(&a.parse_duration_ms).then_with(|| a.path.cmp(&b.path))
    });
    sorted
        .into_iter()
        .take(limit)
        .map(|m| SlowestFileEntry {
            path: m.path.clone(),
            parse_duration_ms: m.parse_duration_ms,
            line_count: m.line_count,
        })
        .collect()
}

/// Median error-node density (errors per 1k LOC) across dirty files.
///
/// Considers only files with `error_node_count > 0` and `line_count > 0`.
/// Returns `None` when no such files exist (e.g., a fully clean corpus or
/// a run where line counts are unavailable). Clean files would skew the
/// median toward zero and hide the per-file severity signal, so they are
/// intentionally excluded.
fn compute_median_error_density(measurements: &[FileMeasurement]) -> Option<f64> {
    let mut densities: Vec<f64> = measurements
        .iter()
        .filter(|m| m.error_node_count > 0 && m.line_count > 0)
        .map(|m| (m.error_node_count as f64 / m.line_count as f64) * 1000.0)
        .collect();

    if densities.is_empty() {
        return None;
    }
    densities.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let mid = densities.len() / 2;
    let median = if densities.len().is_multiple_of(2) {
        (densities[mid - 1] + densities[mid]) / 2.0
    } else {
        densities[mid]
    };
    Some(median)
}

/// Run the corpus sweep with the given configuration
pub fn run(config: SweepConfig) -> Result<()> {
    let start_time = Instant::now();

    // Determine corpus profile and file list
    let default_profile =
        if config.manifest_path.is_some() { "common".to_string() } else { "system".to_string() };
    let corpus_profile = config.corpus_profile.clone().unwrap_or(default_profile);

    let discovery_start = Instant::now();
    let pm_files = if let Some(ref manifest) = config.manifest_path {
        resolve_manifest_modules(manifest, &config.manifest_perl5lib, 6)?
    } else {
        discover_pm_files(&config.corpus_roots)
    };
    let discovery_ms = discovery_start.elapsed().as_millis() as u64;

    let use_manifest = config.manifest_path.is_some();
    if pm_files.is_empty() {
        if use_manifest {
            println!("No modules resolved from manifest.");
        } else {
            println!("No .pm files found in specified roots.");
            println!("Searched: {:?}", config.corpus_roots);
        }
        return Ok(());
    }

    if use_manifest {
        println!("Resolved {} modules from manifest", pm_files.len());
    } else {
        println!("Found {} .pm files across {} roots", pm_files.len(), config.corpus_roots.len());
    }

    // Parse each file
    let progress = ProgressBar::new(pm_files.len() as u64);
    progress.set_style(
        ProgressStyle::default_bar()
            .template("{spinner:.green} [{bar:40.cyan/blue}] {pos}/{len} ({percent}%) {msg}")
            .unwrap_or_else(|_| ProgressStyle::default_bar())
            .progress_chars("=>-"),
    );

    let mut total_files = 0usize;
    let mut files_unreadable = 0usize;
    let mut clean_files = 0usize;
    let mut files_with_errors = 0usize;
    let mut total_dirty_files = 0usize;
    let mut files_with_structured_recovery_only = 0usize;
    let mut files_with_error_nodes = 0usize;
    let mut files_with_catastrophic_parse_failure = 0usize;
    let mut total_error_nodes = 0usize;
    let mut recovered_node_count = 0usize;
    let mut first_unrecovered_error_node_buckets: BTreeMap<String, usize> = BTreeMap::new();
    let mut first_error_buckets: BTreeMap<String, usize> = BTreeMap::new();
    let mut files_by_bucket: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut file_results: Vec<FileResult> = Vec::new();

    // Phase-timing accumulators (nanoseconds to avoid rounding when summing
    // many small per-file durations; converted to ms once at the end).
    let mut file_io_ns: u128 = 0;
    let mut parse_ns: u128 = 0;

    // Per-file measurements used to build the slowest-file report and to
    // compute median error density per 1k LOC. Kept in memory always (not
    // gated by verbose) so receipts can include the derived aggregates
    // without paying the verbose-serialization cost.
    let mut measurements: Vec<FileMeasurement> = Vec::with_capacity(pm_files.len());

    for path in &pm_files {
        total_files += 1;
        let portable_path = portable_report_path(path);
        progress.set_message(
            path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
        );

        let io_start = Instant::now();
        let read_result = fs::read_to_string(path);
        file_io_ns += io_start.elapsed().as_nanos();

        let source = match read_result {
            Ok(s) => s,
            Err(_) => {
                files_unreadable += 1;
                if config.verbose {
                    file_results.push(FileResult {
                        path: portable_path.clone(),
                        status: "unreadable".to_string(),
                        error_node_count: 0,
                        first_error: None,
                        recovered_count: None,
                        parse_duration_ms: None,
                        line_count: None,
                    });
                }
                progress.inc(1);
                continue;
            }
        };

        let line_count = source.lines().count();

        // Parse — wall-time the parse call itself (post-read).
        let parse_start = Instant::now();
        let mut parser = Parser::new(&source);
        let parse_result = parser.parse();
        let parse_elapsed = parse_start.elapsed();
        parse_ns += parse_elapsed.as_nanos();
        let parse_duration_ms = parse_elapsed.as_millis() as u64;

        let ast = match parse_result {
            Ok(ast) => ast,
            Err(_) => {
                // Catastrophic failure (recursion limit etc.) — separate from AST ERROR nodes.
                files_with_errors += 1;
                total_dirty_files += 1;
                files_with_catastrophic_parse_failure += 1;
                measurements.push(FileMeasurement {
                    path: portable_path.clone(),
                    parse_duration_ms,
                    line_count,
                    error_node_count: 0,
                });
                if config.verbose {
                    file_results.push(FileResult {
                        path: portable_path.clone(),
                        status: "catastrophic".to_string(),
                        error_node_count: 0,
                        first_error: None,
                        recovered_count: Some(0),
                        parse_duration_ms: Some(parse_duration_ms),
                        line_count: Some(line_count),
                    });
                }
                progress.inc(1);
                continue;
            }
        };

        let errors: Vec<ParseError> = parser.errors().to_vec();
        let salvage = RecoverySalvageProfile::from_parse(&ast, &errors, false);

        measurements.push(FileMeasurement {
            path: portable_path.clone(),
            parse_duration_ms,
            line_count,
            error_node_count: salvage.error_node_count,
        });

        recovered_node_count = recovered_node_count.saturating_add(salvage.recovered_count);
        match salvage.class {
            RecoverySalvageClass::Clean => {
                clean_files += 1;
                if config.verbose {
                    file_results.push(FileResult {
                        path: portable_path.clone(),
                        status: "clean".to_string(),
                        error_node_count: 0,
                        first_error: None,
                        recovered_count: Some(0),
                        parse_duration_ms: Some(parse_duration_ms),
                        line_count: Some(line_count),
                    });
                }
            }
            RecoverySalvageClass::StructuredRecoveryOnly => {
                files_with_errors += 1;
                total_dirty_files += 1;
                files_with_structured_recovery_only += 1;
                if config.verbose {
                    file_results.push(FileResult {
                        path: portable_path.clone(),
                        status: "recovered".to_string(),
                        error_node_count: 0,
                        first_error: None,
                        recovered_count: Some(salvage.recovered_count),
                        parse_duration_ms: Some(parse_duration_ms),
                        line_count: Some(line_count),
                    });
                }
            }
            RecoverySalvageClass::ErrorNodesPresent => {
                files_with_errors += 1;
                total_dirty_files += 1;
                files_with_error_nodes += 1;
                total_error_nodes = total_error_nodes.saturating_add(salvage.error_node_count);
                let first = salvage.first_unrecovered_error_node.as_deref().unwrap_or("unknown");
                let bucket = normalize_error_bucket(first);
                *first_unrecovered_error_node_buckets.entry(bucket.clone()).or_default() += 1;
                *first_error_buckets.entry(bucket.clone()).or_default() += 1;
                files_by_bucket.entry(bucket.clone()).or_default().push(portable_path.clone());
                if config.verbose {
                    file_results.push(FileResult {
                        path: portable_path.clone(),
                        status: "errors".to_string(),
                        error_node_count: salvage.error_node_count,
                        first_error: Some(bucket),
                        recovered_count: Some(salvage.recovered_count),
                        parse_duration_ms: Some(parse_duration_ms),
                        line_count: Some(line_count),
                    });
                }
            }
            RecoverySalvageClass::CatastrophicFailure => {
                // This arm is unreachable in this branch: `from_parse` is always
                // called with `catastrophic=false` here.  True catastrophic failures
                // are handled above via the `Err(_)` arm which calls `continue`.
                // Keeping the arm to satisfy the exhaustive match; clippy will flag
                // it as unreachable if the enum ever gains a structural invariant.
                files_with_errors += 1;
                total_dirty_files += 1;
                files_with_catastrophic_parse_failure += 1;
            }
        }

        progress.inc(1);
    }

    progress.finish_and_clear();

    let elapsed = start_time.elapsed();
    let commit = get_git_commit();

    let phase_timings = PhaseTimings {
        discovery_ms,
        file_io_ms: (file_io_ns / 1_000_000) as u64,
        parse_ms: (parse_ns / 1_000_000) as u64,
        total_ms: elapsed.as_millis() as u64,
    };
    let median_error_density_per_1k_loc = compute_median_error_density(&measurements);
    let recovery_salvage_rate = if total_dirty_files == 0 {
        None
    } else {
        Some(files_with_structured_recovery_only as f64 / total_dirty_files as f64)
    };
    let slowest_files = top_n_slowest(&measurements, SLOWEST_FILES_LIMIT);

    let report = SweepReport {
        schema_version: "1.3.0".to_string(),
        commit,
        timestamp: chrono::Utc::now().to_rfc3339(),
        corpus_profile: corpus_profile.clone(),
        corpus_roots: if use_manifest {
            vec![config.manifest_path.as_ref().map(|p| portable_report_path(p)).unwrap_or_default()]
        } else {
            config.base_roots.iter().map(|p| portable_report_path(p)).collect()
        },
        resolved_roots_count: if use_manifest { pm_files.len() } else { config.corpus_roots.len() },
        perl_version: get_perl_version(),
        total_files,
        files_unreadable,
        clean_files,
        files_with_errors,
        total_dirty_files,
        files_with_structured_recovery_only,
        files_with_error_nodes,
        files_with_catastrophic_parse_failure,
        total_error_nodes,
        recovered_node_count,
        first_unrecovered_error_node_buckets,
        first_error_buckets,
        files_by_bucket,
        file_results: if config.verbose { file_results } else { Vec::new() },
        elapsed_secs: elapsed.as_secs_f64(),
        phase_timings: Some(phase_timings),
        median_error_density_per_1k_loc,
        recovery_salvage_rate,
        slowest_files,
    };

    // Print summary
    print_summary(&report);

    // Write output if requested
    if let Some(ref output_path) = config.output_path {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent).context("Failed to create output directory")?;
        }
        let json = serde_json::to_string_pretty(&report).context("Failed to serialize report")?;
        fs::write(output_path, json).context("Failed to write report file")?;
        println!("\nReport written to: {}", output_path.display());
    }

    // Write receipt if requested
    if config.receipt {
        let receipt_path = receipt_path_for_profile(&corpus_profile);
        if let Some(parent) = receipt_path.parent() {
            fs::create_dir_all(parent).context("Failed to create receipt directory")?;
        }
        let json = serde_json::to_string_pretty(&report).context("Failed to serialize receipt")?;
        fs::write(&receipt_path, json).context("Failed to write receipt file")?;
        eprintln!("Receipt written to: {}", receipt_path.display());
    }

    // Enforcement: strict clean for manifest mode, ratchet for system mode
    if use_manifest && config.enforce {
        let violations = enforce_strict_clean(&report);
        if !violations.is_empty() {
            println!("\n--- Strict clean violations ---");
            for v in &violations {
                println!(
                    "  VIOLATION: {} — expected: {}, actual: {}",
                    v.metric, v.baseline_value, v.current_value
                );
            }
            return Err(color_eyre::eyre::eyre!(
                "Common corpus strict enforcement failed: {} violation(s) detected",
                violations.len(),
            ));
        }
        println!("Strict clean: all {} files parse without errors", report.total_files);
    }

    // Baseline comparison and ratchet enforcement (system mode)
    if let Some(ref baseline_path) = config.baseline_path {
        let baseline_json =
            fs::read_to_string(baseline_path).context("Failed to read baseline file")?;
        let baseline: SweepReport =
            serde_json::from_str(&baseline_json).context("Failed to parse baseline JSON")?;

        println!("\n--- Baseline comparison ---");
        println!(
            "Baseline: {} clean / {} total ({:.1}%)",
            baseline.clean_files,
            baseline.total_files,
            100.0 * baseline.clean_files as f64 / baseline.total_files.max(1) as f64,
        );
        println!(
            "Current:  {} clean / {} total ({:.1}%)",
            report.clean_files,
            report.total_files,
            100.0 * report.clean_files as f64 / report.total_files.max(1) as f64,
        );

        let delta = report.clean_files as i64 - baseline.clean_files as i64;
        if delta > 0 {
            println!("Result: +{delta} clean files (improvement)");
        } else if delta < 0 {
            println!("Result: {delta} clean files (REGRESSION)");
        } else {
            println!("Result: no change");
        }

        if config.enforce {
            let violations = enforce_ratchet(&report, &baseline);
            if !violations.is_empty() {
                println!("\n--- Ratchet violations ---");
                for v in &violations {
                    println!(
                        "  VIOLATION: {} — baseline: {}, current: {}",
                        v.metric, v.baseline_value, v.current_value
                    );
                }
                return Err(color_eyre::eyre::eyre!(
                    "Ratchet enforcement failed: {} violation(s) detected",
                    violations.len(),
                ));
            }
            println!("Ratchet: all checks passed");
        }
    }

    Ok(())
}

/// Enforce multi-metric ratchet between current report and baseline.
///
/// Returns a list of violations (empty means all checks passed).
pub fn enforce_ratchet(report: &SweepReport, baseline: &SweepReport) -> Vec<RatchetViolation> {
    let mut violations = Vec::new();

    // 1. Crash count must be 0
    let crash_count = report.files_with_catastrophic_parse_failure;
    if crash_count > 0 {
        violations.push(RatchetViolation {
            metric: "crash_count".to_string(),
            baseline_value: "0".to_string(),
            current_value: crash_count.to_string(),
        });
    }

    // 2. Unreadable count must not increase
    if report.files_unreadable > baseline.files_unreadable {
        violations.push(RatchetViolation {
            metric: "files_unreadable".to_string(),
            baseline_value: baseline.files_unreadable.to_string(),
            current_value: report.files_unreadable.to_string(),
        });
    }

    // 3. Clean-file count must not decrease
    if report.clean_files < baseline.clean_files {
        violations.push(RatchetViolation {
            metric: "clean_files".to_string(),
            baseline_value: baseline.clean_files.to_string(),
            current_value: report.clean_files.to_string(),
        });
    }

    // 4. Total ERROR nodes must not increase
    if report.total_error_nodes > baseline.total_error_nodes {
        violations.push(RatchetViolation {
            metric: "total_error_nodes".to_string(),
            baseline_value: baseline.total_error_nodes.to_string(),
            current_value: report.total_error_nodes.to_string(),
        });
    }

    // 5. Per-bucket: existing bucket counts must not increase (new buckets allowed)
    for (bucket, &baseline_count) in &baseline.first_error_buckets {
        let current_count = report.first_error_buckets.get(bucket).copied().unwrap_or(0);
        if current_count > baseline_count {
            violations.push(RatchetViolation {
                metric: format!("bucket:{bucket}"),
                baseline_value: baseline_count.to_string(),
                current_value: current_count.to_string(),
            });
        }
    }

    violations
}

/// Discover all .pm files under the given roots
fn discover_pm_files(roots: &[PathBuf]) -> Vec<PathBuf> {
    let mut files = Vec::new();
    for root in roots {
        if !root.exists() {
            continue;
        }
        for entry in WalkDir::new(root).follow_links(true).into_iter().filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "pm") {
                files.push(path.to_path_buf());
            }
        }
    }
    files.sort();
    files
}

/// Normalize error messages into semantic buckets.
///
/// Two-pass approach:
/// 1. Strip position info (both `"Invalid syntax at position N: msg"` and `"msg at N"` formats)
/// 2. Map to semantic bucket names via substring lookup table
pub fn normalize_error_bucket(error: &str) -> String {
    // Pass 1: strip position info
    let stripped = if let Some(ref re) = *RE_SYNTAX_POS {
        if let Some(caps) = re.captures(error) {
            caps.get(1).map(|m| m.as_str().to_string()).unwrap_or_else(|| error.to_string())
        } else if let Some(ref re_at) = *RE_TRAILING_AT {
            re_at.replace(error, "").to_string()
        } else {
            error.to_string()
        }
    } else if let Some(ref re_at) = *RE_TRAILING_AT {
        re_at.replace(error, "").to_string()
    } else {
        error.to_string()
    };

    // Pass 2: map to semantic bucket via first-match substring lookup
    for &(substring, bucket_name) in SEMANTIC_BUCKETS {
        if stripped.contains(substring) {
            return bucket_name.to_string();
        }
    }

    // No match — use position-stripped string as-is
    stripped
}

/// Get the current git commit hash
fn get_git_commit() -> String {
    std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

/// Print a summary of the sweep results.
///
/// Always emits the headline counters and first-error buckets. When the
/// receipt carries the optional schema-1.3.0 fields (phase timings, median
/// error density, slowest-file list, per-file measurements) they are
/// rendered as additional sections.
pub fn print_summary(report: &SweepReport) {
    let clean_pct = 100.0 * report.clean_files as f64 / report.total_files.max(1) as f64;
    println!("\n=== Parser Corpus Sweep Results ===");
    println!("Total files:       {}", report.total_files);
    println!("Unreadable:        {}", report.files_unreadable);
    println!("Clean (no errors): {} ({:.1}%)", report.clean_files, clean_pct);
    println!("Dirty files:       {}", report.total_dirty_files);
    println!("With errors:       {}", report.files_with_errors);
    println!("  - Structured recovery only: {}", report.files_with_structured_recovery_only);
    println!("  - With ERROR nodes:         {}", report.files_with_error_nodes);
    println!("  - Catastrophic parse fail:  {}", report.files_with_catastrophic_parse_failure);
    println!("Recovered nodes:   {}", report.recovered_node_count);
    println!("Total ERROR nodes: {}", report.total_error_nodes);
    println!("Elapsed:           {:.1}s", report.elapsed_secs);

    if let Some(ref timings) = report.phase_timings {
        println!("\n--- Phase timings ---");
        println!("  Discovery:   {:>7} ms", timings.discovery_ms);
        println!("  File I/O:    {:>7} ms", timings.file_io_ms);
        println!("  Parse:       {:>7} ms", timings.parse_ms);
        println!("  Total:       {:>7} ms", timings.total_ms);
    }

    if let Some(density) = report.median_error_density_per_1k_loc {
        println!("\nMedian error density (dirty files): {density:.2} errors / 1k LOC");
    }
    if let Some(salvage_rate) = report.recovery_salvage_rate {
        println!("Recovery salvage rate: {:.1}%", salvage_rate * 100.0);
    }

    if !report.slowest_files.is_empty() {
        println!("\n--- Top {} slowest files by parse time ---", report.slowest_files.len());
        for entry in &report.slowest_files {
            println!(
                "  {:>5} ms  ({:>6} LOC)  {}",
                entry.parse_duration_ms, entry.line_count, entry.path,
            );
        }
    }

    if !report.file_results.is_empty() {
        // Verbose mode only: emit a top-20-by-error-count report drawn
        // from file_results (the only place error counts are retained
        // per file outside the run-time measurements buffer).
        let mut by_errors: Vec<&FileResult> =
            report.file_results.iter().filter(|r| r.error_node_count > 0).collect();
        if !by_errors.is_empty() {
            by_errors.sort_by(|a, b| {
                b.error_node_count.cmp(&a.error_node_count).then_with(|| a.path.cmp(&b.path))
            });
            let limit = SLOWEST_FILES_LIMIT.min(by_errors.len());
            println!("\n--- Top {limit} files by error-node count ---");
            for entry in by_errors.iter().take(limit) {
                println!("  {:>5} errors  {}", entry.error_node_count, entry.path);
            }
        }
    }

    if !report.first_unrecovered_error_node_buckets.is_empty() {
        println!("\n--- First unrecovered ERROR-node buckets (top 20) ---");
        let mut sorted: Vec<_> = report.first_unrecovered_error_node_buckets.iter().collect();
        sorted.sort_by(|a, b| b.1.cmp(a.1));
        for (i, (bucket, count)) in sorted.iter().enumerate() {
            if i >= 20 {
                let remaining: usize = sorted[20..].iter().map(|(_, c)| *c).sum();
                println!("  ... and {} more buckets ({} files)", sorted.len() - 20, remaining);
                break;
            }
            println!("  {:>4} {}", count, bucket);
        }
    }
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    /// Helper to create a test report with sensible defaults
    fn test_report(
        clean_files: usize,
        files_with_errors: usize,
        total_error_nodes: usize,
        files_unreadable: usize,
        first_error_buckets: BTreeMap<String, usize>,
    ) -> SweepReport {
        SweepReport {
            schema_version: "1.2.0".to_string(),
            commit: "abc".to_string(),
            timestamp: "now".to_string(),
            corpus_profile: "system".to_string(),
            corpus_roots: vec![],
            resolved_roots_count: 0,
            perl_version: "unknown".to_string(),
            total_files: clean_files + files_with_errors + files_unreadable,
            files_unreadable,
            clean_files,
            files_with_errors,
            total_dirty_files: files_with_errors,
            files_with_structured_recovery_only: 0,
            files_with_error_nodes: files_with_errors,
            files_with_catastrophic_parse_failure: 0,
            total_error_nodes,
            recovered_node_count: 0,
            first_unrecovered_error_node_buckets: first_error_buckets.clone(),
            first_error_buckets,
            files_by_bucket: BTreeMap::new(),
            file_results: vec![],
            elapsed_secs: 1.0,
            phase_timings: None,
            median_error_density_per_1k_loc: None,
            recovery_salvage_rate: None,
            slowest_files: vec![],
        }
    }

    use perl_parser::SourceLocation;

    /// Helper to create a Node with the given kind at the given byte offset.
    fn node_at(kind: NodeKind, start: usize, end: usize) -> Node {
        Node::new(kind, SourceLocation { start, end })
    }

    #[test]
    fn test_collect_error_summary_no_errors() {
        let root = node_at(
            NodeKind::Program {
                statements: vec![node_at(NodeKind::Number { value: "42".to_string() }, 0, 2)],
            },
            0,
            2,
        );
        let summary = collect_error_summary(&root);
        assert_eq!(summary.count, 0);
        assert!(summary.first_message.is_none());
    }

    #[test]
    fn test_collect_error_summary_single_error() {
        let root = node_at(
            NodeKind::Program {
                statements: vec![node_at(
                    NodeKind::Error {
                        message: "expected semicolon".to_string(),
                        expected: vec![],
                        found: None,
                        partial: None,
                    },
                    5,
                    10,
                )],
            },
            0,
            10,
        );
        let summary = collect_error_summary(&root);
        assert_eq!(summary.count, 1);
        assert_eq!(summary.first_message.as_deref(), Some("expected semicolon"));
    }

    #[test]
    fn test_collect_error_summary_multiple_errors_picks_earliest() {
        let root = node_at(
            NodeKind::Program {
                statements: vec![
                    node_at(
                        NodeKind::Error {
                            message: "later error".to_string(),
                            expected: vec![],
                            found: None,
                            partial: None,
                        },
                        20,
                        30,
                    ),
                    node_at(
                        NodeKind::Error {
                            message: "earlier error".to_string(),
                            expected: vec![],
                            found: None,
                            partial: None,
                        },
                        5,
                        15,
                    ),
                ],
            },
            0,
            30,
        );
        let summary = collect_error_summary(&root);
        assert_eq!(summary.count, 2);
        assert_eq!(summary.first_message.as_deref(), Some("earlier error"));
    }

    #[test]
    fn test_collect_error_summary_error_in_partial() {
        // Error node with a partial subtree containing another Error
        let inner_error = node_at(
            NodeKind::Error {
                message: "inner error".to_string(),
                expected: vec![],
                found: None,
                partial: None,
            },
            15,
            20,
        );
        let outer_error = node_at(
            NodeKind::Error {
                message: "outer error".to_string(),
                expected: vec![],
                found: None,
                partial: Some(Box::new(inner_error)),
            },
            5,
            20,
        );
        let root = node_at(NodeKind::Program { statements: vec![outer_error] }, 0, 20);
        let summary = collect_error_summary(&root);
        assert_eq!(summary.count, 2);
        // Outer error at offset 5 wins over inner at offset 15
        assert_eq!(summary.first_message.as_deref(), Some("outer error"));
    }

    #[test]
    fn test_normalize_error_bucket_trailing_at() {
        // Position suffix stripped, then mapped to semantic bucket
        assert_eq!(
            normalize_error_bucket("expected ']', found end of input at 42"),
            "unclosed_bracket",
        );
        // Just position stripping, no semantic match
        assert_eq!(normalize_error_bucket("some rare error at 99"), "some rare error",);
    }

    #[test]
    fn test_normalize_error_bucket_passthrough() {
        assert_eq!(
            normalize_error_bucket("some new error we haven't seen"),
            "some new error we haven't seen",
        );
    }

    #[test]
    fn test_normalize_error_bucket_syntax_position() {
        // After removing the phantom "catastrophic_backtracking" bucket (#2029),
        // the RE_SYNTAX_POS regex strips "Invalid syntax at position N:" and the
        // remaining message falls through verbatim (no matching bucket).
        assert_eq!(
            normalize_error_bucket(
                "Invalid syntax at position 1006: Potential catastrophic backtracking detected"
            ),
            "Potential catastrophic backtracking detected",
        );
    }

    #[test]
    fn test_nested_quantifier_diagnostic_is_not_catastrophic_bucket() {
        // The actual message the parser records for nested quantifiers is
        // "Nested quantifiers detected (possible backtracking risk)" (via record_error,
        // never NodeKind::Error). It must NOT map to the removed "catastrophic_backtracking"
        // bucket — it falls through to verbatim passthrough after position stripping.
        let real_diag = "Invalid syntax at position 42: Nested quantifiers detected (possible backtracking risk)";
        let result = normalize_error_bucket(real_diag);
        assert_eq!(result, "Nested quantifiers detected (possible backtracking risk)");
        assert_ne!(result, "catastrophic_backtracking");
    }

    #[test]
    fn test_normalize_error_bucket_unclosed_brace_semicolon() {
        assert_eq!(
            normalize_error_bucket("Unexpected token: expected '}', found ';' at 42"),
            "unclosed_brace_semicolon",
        );
    }

    #[test]
    fn test_semantic_bucket_mapping() {
        let cases = [
            // Display-name format (current parser output uses TokenKind::display_name())
            ("expected expression, found '=>' at 10", "unexpected_fat_arrow_expr"),
            ("expected expression, found '->'", "unexpected_arrow_expr"),
            ("expected expression, found '/' at 5", "unexpected_slash_expr"),
            ("expected expression, found '?'", "unexpected_question_expr"),
            ("expected expression, found 'return' at 99", "unexpected_return_expr"),
            ("expected expression, found SomeOtherToken", "unexpected_token_in_expr"),
            ("expected '}', found end of input", "unclosed_brace_eof"),
            ("expected '}', found ';'", "unclosed_brace_semicolon"),
            ("expected '}'", "unclosed_brace"),
            ("expected ')', found identifier", "unclosed_paren_identifier"),
            ("expected ')'", "unclosed_paren"),
            ("expected ']'", "unclosed_bracket"),
            ("expected '('", "expected_left_paren"),
            ("expected '{'", "expected_left_brace"),
            ("expected ';'", "expected_semicolon"),
            ("expected ':'", "expected_colon"),
            ("expected identifier", "expected_identifier"),
            ("expected ','", "expected_comma"),
            ("Expected variable, found something", "expected_variable"),
            // "expected_import_item" removed (#2029): phantom bucket — no parser code
            // generates "Expected string or identifier in import".
            ("Expected comma or closing parenthesis in signature", "signature_param"),
            ("Expected comma or closing parenthesis", "expected_comma_or_close_paren"),
            ("Expected module name or version string", "expected_module_name"),
            ("Expected '>' to close angle bracket", "unclosed_angle"),
            ("Substitution operator should be s///", "substitution_misparse"),
            ("Invalid syntax at position 42: Expected variable, found X", "expected_variable"),
            // New entries added by issue #2587
            ("expected expression, found ']'", "unexpected_rbracket_expr"),
            ("expected expression, found 'if'", "unexpected_token_if"),
            ("expected expression, found 'my'", "unexpected_token_my"),
            ("expected expression, found 'our'", "unexpected_token_our"),
            ("expected expression, found 'local'", "unexpected_token_local"),
            ("expected expression, found 'sub'", "unexpected_token_sub"),
            ("expected expression, found 'package'", "unexpected_token_package"),
            ("expected expression, found 'eval'", "unexpected_token_eval"),
            ("expected expression, found 'do'", "unexpected_token_do"),
            ("expected expression, found 'next'", "unexpected_token_next"),
            ("expected expression, found 'last'", "unexpected_token_last"),
            ("expected expression, found 'redo'", "unexpected_token_redo"),
            ("expected expression, found '='", "unexpected_assign_expr"),
            ("expected expression, found '=='", "unexpected_eq_expr"),
            ("expected expression, found '=~'", "unexpected_match_expr"),
            ("expected expression, found '..'", "unexpected_range_expr"),
        ];

        for (input, expected) in cases {
            assert_eq!(normalize_error_bucket(input), expected, "Failed for input: {input}",);
        }
    }

    #[test]
    fn test_double_slash_not_swallowed_by_slash_bucket() {
        // '//' must not match unexpected_slash_expr — the '//' entry must precede '/' in
        // SEMANTIC_BUCKETS if it is ever added. This test documents the ordering constraint
        // and will need updating when a '//' bucket entry is added.
        // NOTE: "expected expression, found '//'" does NOT contain "found '/'" literally —
        // the quotes around '//' mean it won't match the "'/" substring in the '/' entry.
        // Verify: '//' is caught by unexpected_token_in_expr (no dedicated entry yet).
        assert_eq!(
            normalize_error_bucket("expected expression, found '//'"),
            "unexpected_token_in_expr",
        );
    }

    #[test]
    fn test_eq_not_swallowed_by_assign_bucket() {
        // '==' message must map to unexpected_eq_expr, not unexpected_assign_expr.
        // The quoted form "found '=='" does NOT contain "found '='" as a substring
        // (the trailing quote disambiguates), but keeping '==' before '=' is defensive
        // in case the message format ever changes to unquoted tokens.
        assert_eq!(normalize_error_bucket("expected expression, found '=='"), "unexpected_eq_expr",);
        // '=~' must also route to its own bucket, not '='
        assert_eq!(
            normalize_error_bucket("expected expression, found '=~'"),
            "unexpected_match_expr",
        );
        // '=' itself still routes correctly
        assert_eq!(
            normalize_error_bucket("expected expression, found '='"),
            "unexpected_assign_expr",
        );
    }

    #[test]
    fn test_enforce_ratchet_no_violations() {
        let report = test_report(
            80,
            18,
            25,
            2,
            BTreeMap::from([("unclosed_brace".to_string(), 10), ("unclosed_paren".to_string(), 8)]),
        );

        let baseline = report.clone();
        let violations = enforce_ratchet(&report, &baseline);
        assert!(violations.is_empty(), "Expected no violations when report equals baseline");
    }

    #[test]
    fn test_enforce_ratchet_regression() {
        let baseline =
            test_report(80, 18, 25, 2, BTreeMap::from([("unclosed_brace".to_string(), 10)]));

        let report = SweepReport {
            clean_files: 75,       // decreased (violation)
            total_error_nodes: 30, // increased (violation)
            files_unreadable: 3,   // increased (violation)
            ..baseline.clone()
        };

        let violations = enforce_ratchet(&report, &baseline);
        assert_eq!(violations.len(), 3, "Expected 3 violations");

        let metrics: Vec<&str> = violations.iter().map(|v| v.metric.as_str()).collect();
        assert!(metrics.contains(&"files_unreadable"));
        assert!(metrics.contains(&"clean_files"));
        assert!(metrics.contains(&"total_error_nodes"));
    }

    #[test]
    fn test_enforce_ratchet_per_bucket() {
        let baseline = test_report(
            80,
            20,
            20,
            0,
            BTreeMap::from([("unclosed_brace".to_string(), 10), ("unclosed_paren".to_string(), 5)]),
        );

        let report = SweepReport {
            first_error_buckets: BTreeMap::from([
                ("unclosed_brace".to_string(), 12), // increased (violation)
                ("unclosed_paren".to_string(), 3),  // decreased (ok)
                ("new_bucket".to_string(), 5),      // new bucket (ok)
            ]),
            ..baseline.clone()
        };

        let violations = enforce_ratchet(&report, &baseline);
        assert_eq!(violations.len(), 1, "Expected 1 per-bucket violation");
        assert_eq!(violations[0].metric, "bucket:unclosed_brace");
        assert_eq!(violations[0].baseline_value, "10");
        assert_eq!(violations[0].current_value, "12");
    }

    #[test]
    fn test_enforce_ratchet_crash_count() {
        let baseline = test_report(80, 20, 20, 0, BTreeMap::new());

        let report = SweepReport { files_with_catastrophic_parse_failure: 2, ..baseline.clone() };

        let violations = enforce_ratchet(&report, &baseline);
        let crash_violation = violations.iter().find(|v| v.metric == "crash_count");
        assert!(crash_violation.is_some(), "Expected crash_count violation");
    }

    #[test]
    fn test_discover_nonexistent_root() {
        let files = discover_pm_files(&[PathBuf::from("/nonexistent/path")]);
        assert!(files.is_empty());
    }

    #[test]
    fn test_backward_compatible_deserialization() {
        // Old 1.0.0 schema without the new fields should deserialize cleanly
        let old_json = r#"{
            "schema_version": "1.0.0",
            "commit": "abc",
            "timestamp": "now",
            "corpus_roots": ["/usr/share/perl"],
            "total_files": 100,
            "files_unreadable": 0,
            "clean_files": 80,
            "files_with_errors": 20,
            "total_error_nodes": 30,
            "first_error_buckets": {},
            "elapsed_secs": 1.0
        }"#;
        let report: SweepReport = serde_json::from_str(old_json).expect("should deserialize");
        assert_eq!(report.corpus_profile, "system");
        assert_eq!(report.resolved_roots_count, 0);
        assert_eq!(report.perl_version, "unknown");
    }

    #[test]
    fn test_receipt_path_for_profile_uses_profile_name() {
        assert_eq!(
            receipt_path_for_profile("system"),
            PathBuf::from("target/receipts/system-corpus-sweep.json")
        );
        assert_eq!(
            receipt_path_for_profile("cpan"),
            PathBuf::from("target/receipts/cpan-corpus-sweep.json")
        );
        assert_eq!(
            receipt_path_for_profile("cpan-common"),
            PathBuf::from("target/receipts/cpan-common-corpus-sweep.json")
        );
    }

    #[test]
    fn test_enforce_strict_clean_all_clean() {
        let report = test_report(10, 0, 0, 0, BTreeMap::new());
        let violations = enforce_strict_clean(&report);
        assert!(violations.is_empty(), "Expected no violations for all-clean report");
    }

    #[test]
    fn test_enforce_strict_clean_with_errors() {
        let report = test_report(8, 2, 5, 0, BTreeMap::from([("unclosed_brace".to_string(), 2)]));
        let violations = enforce_strict_clean(&report);
        assert_eq!(
            violations.len(),
            2,
            "Expected 2 violations (files_with_errors + total_error_nodes)"
        );
        let metrics: Vec<&str> = violations.iter().map(|v| v.metric.as_str()).collect();
        assert!(metrics.contains(&"files_with_errors"));
        assert!(metrics.contains(&"total_error_nodes"));
    }

    #[test]
    fn test_enforce_strict_clean_with_unreadable() {
        let report = test_report(9, 0, 0, 1, BTreeMap::new());
        let violations = enforce_strict_clean(&report);
        assert_eq!(violations.len(), 1, "Expected 1 violation for unreadable files");
        assert_eq!(violations[0].metric, "files_unreadable");
    }

    #[test]
    fn test_parse_manifest() {
        let dir = std::env::temp_dir().join("test_parse_manifest");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("test-manifest.txt");
        fs::write(&manifest, "# Comment line\n\nExporter\nCarp\n# Another comment\nFile::Find\n")
            .expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        assert_eq!(modules, vec!["Exporter", "Carp", "File::Find"]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_parse_manifest_empty() {
        let dir = std::env::temp_dir().join("test_parse_manifest_empty");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("empty-manifest.txt");
        fs::write(&manifest, "# Only comments\n\n# Nothing here\n").expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        assert!(modules.is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_resolve_manifest_module_path_uses_existing_direct_path() {
        let dir = std::env::temp_dir().join("test_resolve_manifest_direct_path");
        let _ = fs::create_dir_all(&dir);
        let file = dir.join("Config.pm");
        fs::write(&file, "package Config; 1;\n").expect("write module");

        let resolved = resolve_manifest_module_path_impl(file.to_string_lossy().as_ref(), |_| None)
            .expect("should resolve direct path");
        assert_eq!(resolved, file);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_resolve_manifest_module_path_uses_windows_converter_result() {
        let dir = std::env::temp_dir().join("test_resolve_manifest_windows_converter");
        let _ = fs::create_dir_all(&dir);
        let file = dir.join("Config.pm");
        fs::write(&file, "package Config; 1;\n").expect("write module");

        let resolved =
            resolve_manifest_module_path_impl("/usr/lib/perl5/core_perl/Config.pm", |_| {
                Some(file.clone())
            })
            .expect("should resolve converted path");
        assert_eq!(resolved, file);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_resolve_manifest_module_path_rejects_missing_paths() {
        let dir = std::env::temp_dir().join("test_resolve_manifest_missing_path");
        let _ = fs::create_dir_all(&dir);
        let missing = dir.join("Missing.pm");

        let resolved =
            resolve_manifest_module_path_impl("/usr/lib/perl5/core_perl/Missing.pm", |_| {
                Some(missing.clone())
            });
        assert!(resolved.is_none(), "missing paths should not resolve");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_resolve_corpus_roots_nonexistent() {
        let roots = resolve_corpus_roots(&[PathBuf::from("/nonexistent/base")]);
        // Falls back to the base roots themselves
        assert_eq!(roots, vec![PathBuf::from("/nonexistent/base")]);
    }

    #[test]
    fn test_default_base_roots() {
        let roots = default_base_roots();
        assert_eq!(roots.len(), 3);
    }

    // ── normalize_error_bucket edge cases ──────────────────────────────

    #[test]
    fn test_normalize_error_bucket_empty_string() {
        // Empty input should pass through as-is
        assert_eq!(normalize_error_bucket(""), "");
    }

    #[test]
    fn test_normalize_error_bucket_unknown_passthrough() {
        // The default value used when first_message is None
        assert_eq!(normalize_error_bucket("unknown"), "unknown");
    }

    #[test]
    fn test_normalize_error_bucket_syntax_pos_with_trailing_at() {
        // "Invalid syntax at position N:" strips outer wrapper first,
        // so inner trailing " at N" is NOT stripped by the second regex
        // (the first regex branch succeeds, so RE_TRAILING_AT is skipped).
        let result = normalize_error_bucket(
            "Invalid syntax at position 42: expected ';', found end of input at 99",
        );
        assert_eq!(result, "expected_semicolon");
    }

    #[test]
    fn test_normalize_error_bucket_only_position_suffix() {
        // Message that is essentially only a trailing position marker
        assert_eq!(normalize_error_bucket("at 42"), "at 42");
        // A more realistic message with " at N" trimmed leaving a short string
        assert_eq!(normalize_error_bucket("oops at 7"), "oops");
    }

    #[test]
    fn test_normalize_error_bucket_multiple_at_suffixes() {
        // Only the last " at N" should be stripped by RE_TRAILING_AT
        assert_eq!(
            normalize_error_bucket("something at 10 and more at 20"),
            "something at 10 and more",
        );
    }

    #[test]
    fn test_normalize_error_bucket_syntax_pos_no_semantic_match() {
        // Strip "Invalid syntax at position N:" wrapper, but inner message
        // doesn't match any semantic bucket -- should pass through stripped.
        assert_eq!(
            normalize_error_bucket("Invalid syntax at position 500: some rare exotic error"),
            "some rare exotic error",
        );
    }

    #[test]
    fn test_normalize_error_bucket_whitespace_preserved() {
        // Ensure leading/trailing whitespace in the message is preserved
        // (no implicit trimming)
        let result = normalize_error_bucket("  expected ';', found end of input  ");
        assert_eq!(result, "expected_semicolon");
    }

    #[test]
    fn test_normalize_error_bucket_all_semantic_buckets_reachable() {
        // NOTE: This test proves the bucket TABLE is internally consistent (each key matches
        // itself). It does NOT verify that real parser output triggers these buckets.
        // Use test_unexpected_eof_expr_from_real_parser_format and similar tests for that.
        //
        // Verify that every entry in SEMANTIC_BUCKETS can be triggered
        for &(substring, bucket_name) in SEMANTIC_BUCKETS {
            let result = normalize_error_bucket(substring);
            assert_eq!(
                result, bucket_name,
                "Direct substring '{}' should map to bucket '{}'",
                substring, bucket_name,
            );
        }
    }

    #[test]
    fn test_unexpected_eof_expr_from_real_parser_format() {
        // Real parser output: ParseError::UnexpectedToken with expected="expression",
        // found=TokenKind::Eof.display_name()="end of input" (NO single quotes).
        // Formatted as "expected expression, found end of input at position N".
        // The bucket key must NOT have single quotes around "end of input".
        assert_eq!(
            normalize_error_bucket("expected expression, found end of input at position 42"),
            "unexpected_eof_expr",
        );
    }

    #[test]
    fn test_unexpected_eof_expr_old_quoted_key_does_not_match() {
        // Verifies the real parser output does not contain the old broken quoted key.
        // TokenKind::Eof.display_name() returns "end of input" without single quotes.
        let broken_key = "expected expression, found 'end of input'";
        let real_output = "expected expression, found end of input at position 42";
        assert!(
            !real_output.contains(broken_key),
            "Quoted key should not match real parser output — quotes are not emitted by Eof.display_name()",
        );
    }

    #[test]
    fn test_substitution_modifier_buckets() {
        // The prefix "Invalid substitution modifier" must match all modifier variants,
        // not just one specific letter — confirm two distinct letters both route correctly.
        assert_eq!(
            normalize_error_bucket(
                "Invalid substitution modifier 'T'. Valid modifiers are: g, i, m, s, x, o, e, r"
            ),
            "invalid_substitution_modifier",
        );
        assert_eq!(
            normalize_error_bucket(
                "Invalid substitution modifier 'b'. Valid modifiers are: g, i, m, s, x, o, e, r"
            ),
            "invalid_substitution_modifier",
        );
        assert_eq!(
            normalize_error_bucket("Missing closing delimiter in substitution"),
            "unclosed_substitution_delimiter",
        );
    }

    #[test]
    fn test_normalize_error_bucket_first_match_wins() {
        // "expected expression, found 'return'" should match the specific
        // return bucket, not the generic "unexpected_token_in_expr"
        assert_eq!(
            normalize_error_bucket("expected expression, found 'return'"),
            "unexpected_return_expr",
        );
        // "expected '}', found ';'" should match the specific
        // semicolon bucket, not the generic "unclosed_brace"
        assert_eq!(normalize_error_bucket("expected '}', found ';'"), "unclosed_brace_semicolon",);
    }

    // ── parse_manifest edge cases ──────────────────────────────────────

    #[test]
    fn test_parse_manifest_whitespace_only() {
        let dir = std::env::temp_dir().join("test_parse_manifest_ws_only");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("ws-only.txt");
        fs::write(&manifest, "   \n\t\n  \n").expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        assert!(modules.is_empty(), "Whitespace-only manifest should yield no modules");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_parse_manifest_whitespace_and_comments_only() {
        let dir = std::env::temp_dir().join("test_parse_manifest_ws_comments");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("ws-comments.txt");
        fs::write(&manifest, "  \n# comment 1\n  \t  \n# comment 2\n\n").expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        assert!(modules.is_empty(), "Whitespace+comments-only manifest should yield no modules");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_parse_manifest_trailing_whitespace_on_names() {
        let dir = std::env::temp_dir().join("test_parse_manifest_trailing_ws");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("trailing-ws.txt");
        fs::write(&manifest, "Exporter   \nCarp\t\n  File::Find  \n").expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        // parse_manifest calls .trim() so trailing whitespace should be stripped
        assert_eq!(modules, vec!["Exporter", "Carp", "File::Find"]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_parse_manifest_leading_whitespace_on_names() {
        let dir = std::env::temp_dir().join("test_parse_manifest_leading_ws");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("leading-ws.txt");
        fs::write(&manifest, "  Exporter\n\tCarp\n").expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        assert_eq!(modules, vec!["Exporter", "Carp"]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_parse_manifest_nonexistent_file() {
        let result = parse_manifest(Path::new("/nonexistent/path/manifest.txt"));
        assert!(result.is_err(), "Should error on nonexistent manifest file");
    }

    #[test]
    fn test_parse_manifest_inline_comments_not_stripped() {
        // Verify that `#` in the middle of a line is NOT treated as a comment
        // (only lines starting with `#` after trimming are skipped)
        let dir = std::env::temp_dir().join("test_parse_manifest_inline_comment");
        let _ = fs::create_dir_all(&dir);
        let manifest = dir.join("inline-comment.txt");
        fs::write(&manifest, "Module::Name # not a comment\n").expect("write manifest");
        let modules = parse_manifest(&manifest).expect("parse manifest");
        assert_eq!(modules, vec!["Module::Name # not a comment"]);
        let _ = fs::remove_dir_all(&dir);
    }

    // ── enforce_strict_clean edge cases ────────────────────────────────

    #[test]
    fn test_enforce_strict_clean_all_three_violations() {
        let report = test_report(5, 3, 7, 2, BTreeMap::from([("unclosed_brace".to_string(), 3)]));
        let violations = enforce_strict_clean(&report);
        assert_eq!(
            violations.len(),
            3,
            "Expected violations for unreadable + errors + error_nodes"
        );
        let metrics: Vec<&str> = violations.iter().map(|v| v.metric.as_str()).collect();
        assert!(metrics.contains(&"files_unreadable"));
        assert!(metrics.contains(&"files_with_errors"));
        assert!(metrics.contains(&"total_error_nodes"));
    }

    // ── enforce_ratchet edge cases ─────────────────────────────────────

    #[test]
    fn test_enforce_ratchet_improvement_no_violations() {
        let baseline =
            test_report(80, 20, 30, 2, BTreeMap::from([("unclosed_brace".to_string(), 10)]));
        let report = SweepReport {
            clean_files: 90,                                                          // improved
            files_with_errors: 10,                                                    // improved
            total_error_nodes: 15,                                                    // improved
            files_unreadable: 1,                                                      // improved
            first_error_buckets: BTreeMap::from([("unclosed_brace".to_string(), 5)]), // improved
            ..baseline.clone()
        };
        let violations = enforce_ratchet(&report, &baseline);
        assert!(violations.is_empty(), "Improvements should not trigger violations");
    }

    #[test]
    fn test_enforce_ratchet_bucket_disappeared() {
        // A bucket that existed in the baseline but is absent in current
        // should NOT be a violation (it means the errors were fixed)
        let baseline = test_report(
            80,
            20,
            20,
            0,
            BTreeMap::from([("unclosed_brace".to_string(), 10), ("unclosed_paren".to_string(), 5)]),
        );
        let report = SweepReport {
            first_error_buckets: BTreeMap::from([("unclosed_brace".to_string(), 10)]),
            ..baseline.clone()
        };
        let violations = enforce_ratchet(&report, &baseline);
        assert!(violations.is_empty(), "Disappeared bucket should not be a violation");
    }

    #[test]
    fn test_enforce_ratchet_empty_baselines() {
        let baseline = test_report(0, 0, 0, 0, BTreeMap::new());
        let report = baseline.clone();
        let violations = enforce_ratchet(&report, &baseline);
        assert!(violations.is_empty(), "Empty baselines should have no violations");
    }

    // ── files_by_bucket tests ──────────────────────────────────────────

    #[test]
    fn test_files_by_bucket_populated_for_error_files() {
        // A report where files_by_bucket has known content
        let mut fbb = BTreeMap::new();
        fbb.insert("unclosed_brace".to_string(), vec!["Foo.pm".to_string(), "Bar.pm".to_string()]);
        let report = SweepReport {
            files_by_bucket: fbb,
            ..test_report(8, 2, 3, 0, BTreeMap::from([("unclosed_brace".to_string(), 2)]))
        };
        let files = report.files_by_bucket.get("unclosed_brace").expect("bucket should exist");
        assert_eq!(files.len(), 2);
        assert!(files.contains(&"Foo.pm".to_string()));
    }

    #[test]
    fn test_files_by_bucket_serde_roundtrip() {
        let mut fbb = BTreeMap::new();
        fbb.insert("expected_semicolon".to_string(), vec!["Some/Module.pm".to_string()]);
        let report = SweepReport {
            files_by_bucket: fbb,
            ..test_report(9, 1, 1, 0, BTreeMap::from([("expected_semicolon".to_string(), 1)]))
        };
        let json = serde_json::to_string(&report).expect("serialize");
        let back: SweepReport = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.files_by_bucket, report.files_by_bucket);
    }

    #[test]
    fn test_files_by_bucket_absent_in_old_schema_deserializes_empty() {
        // The existing backward-compat JSON (schema 1.0.0) has no files_by_bucket
        // field — must deserialize as empty BTreeMap.
        let old_json = r#"{
            "schema_version": "1.0.0",
            "commit": "abc",
            "timestamp": "now",
            "corpus_roots": ["/usr/share/perl"],
            "total_files": 100,
            "files_unreadable": 0,
            "clean_files": 80,
            "files_with_errors": 20,
            "total_error_nodes": 30,
            "first_error_buckets": {},
            "elapsed_secs": 1.0
        }"#;
        let report: SweepReport = serde_json::from_str(old_json).expect("deserialize old schema");
        assert!(report.files_by_bucket.is_empty(), "files_by_bucket should default to empty");
    }

    #[test]
    fn test_files_by_bucket_not_examined_by_ratchet() {
        // Different file lists in files_by_bucket with identical counts should not trigger
        // violations — files_by_bucket is informational only, not part of the ratchet.
        let mut fbb_a = BTreeMap::new();
        fbb_a.insert("unclosed_brace".to_string(), vec!["A.pm".to_string()]);
        let mut fbb_b = BTreeMap::new();
        fbb_b.insert("unclosed_brace".to_string(), vec!["B.pm".to_string()]);
        let baseline = SweepReport {
            files_by_bucket: fbb_a,
            ..test_report(9, 1, 1, 0, BTreeMap::from([("unclosed_brace".to_string(), 1)]))
        };
        let report = SweepReport { files_by_bucket: fbb_b, ..baseline.clone() };
        let violations = enforce_ratchet(&report, &baseline);
        assert!(violations.is_empty(), "files_by_bucket changes should not affect ratchet");
    }

    #[test]
    fn test_portable_report_path_relativizes_workspace_paths() {
        let workspace_root = super::super::cpan_corpus::workspace_root();
        let path = workspace_root.join("target/cpan-corpus/lib/perl5/Foo.pm");
        assert_eq!(portable_report_path(&path), "target/cpan-corpus/lib/perl5/Foo.pm");
    }

    #[test]
    fn test_portable_report_path_preserves_external_paths() {
        let path = PathBuf::from("/usr/share/perl/Foo.pm");
        assert_eq!(portable_report_path(&path), "/usr/share/perl/Foo.pm");
    }

    // ── schema 1.3.0: phase timings + slowest-files + median density ───

    fn measurement(path: &str, parse_ms: u64, lines: usize, errors: usize) -> FileMeasurement {
        FileMeasurement {
            path: path.to_string(),
            parse_duration_ms: parse_ms,
            line_count: lines,
            error_node_count: errors,
        }
    }

    #[test]
    fn test_top_n_slowest_empty_input() {
        let slowest = top_n_slowest(&[], 5);
        assert!(slowest.is_empty());
    }

    #[test]
    fn test_top_n_slowest_sorts_descending() {
        let measurements = vec![
            measurement("a.pm", 10, 100, 0),
            measurement("b.pm", 50, 200, 0),
            measurement("c.pm", 30, 150, 0),
        ];
        let slowest = top_n_slowest(&measurements, 10);
        assert_eq!(slowest.len(), 3);
        assert_eq!(slowest[0].path, "b.pm");
        assert_eq!(slowest[0].parse_duration_ms, 50);
        assert_eq!(slowest[1].path, "c.pm");
        assert_eq!(slowest[2].path, "a.pm");
    }

    #[test]
    fn test_top_n_slowest_honors_limit() {
        let measurements = vec![
            measurement("a.pm", 10, 50, 0),
            measurement("b.pm", 20, 50, 0),
            measurement("c.pm", 30, 50, 0),
        ];
        let slowest = top_n_slowest(&measurements, 2);
        assert_eq!(slowest.len(), 2);
        assert_eq!(slowest[0].path, "c.pm");
        assert_eq!(slowest[1].path, "b.pm");
    }

    #[test]
    fn test_top_n_slowest_ties_broken_by_path_deterministically() {
        // Two files with identical parse times must sort by path ascending
        // so repeated runs produce identical receipts.
        let measurements = vec![
            measurement("zeta.pm", 10, 50, 0),
            measurement("alpha.pm", 10, 50, 0),
            measurement("mu.pm", 10, 50, 0),
        ];
        let slowest = top_n_slowest(&measurements, 10);
        assert_eq!(slowest[0].path, "alpha.pm");
        assert_eq!(slowest[1].path, "mu.pm");
        assert_eq!(slowest[2].path, "zeta.pm");
    }

    #[test]
    fn test_compute_median_error_density_empty() {
        assert!(compute_median_error_density(&[]).is_none());
    }

    #[test]
    fn test_compute_median_error_density_all_clean() {
        // Clean files must be excluded so a fully clean corpus returns None.
        let measurements = vec![measurement("a.pm", 1, 100, 0), measurement("b.pm", 1, 200, 0)];
        assert!(compute_median_error_density(&measurements).is_none());
    }

    #[test]
    fn test_compute_median_error_density_ignores_zero_lines() {
        // Division-by-zero guard: a dirty file with no recorded line count
        // must not poison the median.
        let measurements = vec![
            measurement("empty.pm", 1, 0, 5),
            measurement("good.pm", 1, 100, 10), // 100.0 per 1k LOC
        ];
        let density = compute_median_error_density(&measurements).expect("some");
        assert!((density - 100.0).abs() < 1e-6, "expected 100.0, got {density}");
    }

    #[test]
    fn test_compute_median_error_density_odd_count() {
        let measurements = vec![
            measurement("a.pm", 1, 100, 1),  //  10.0
            measurement("b.pm", 1, 1000, 5), //   5.0
            measurement("c.pm", 1, 100, 5),  //  50.0
        ];
        let density = compute_median_error_density(&measurements).expect("some");
        assert!((density - 10.0).abs() < 1e-6);
    }

    #[test]
    fn test_compute_median_error_density_even_count_averages() {
        let measurements = vec![
            measurement("a.pm", 1, 1000, 10), // 10.0
            measurement("b.pm", 1, 1000, 20), // 20.0
        ];
        // median of [10.0, 20.0] = 15.0
        let density = compute_median_error_density(&measurements).expect("some");
        assert!((density - 15.0).abs() < 1e-6, "expected 15.0, got {density}");
    }

    #[test]
    fn test_sweep_report_schema_1_3_0_roundtrip() {
        // New optional fields roundtrip correctly and are emitted with
        // expected JSON keys.
        let report = SweepReport {
            phase_timings: Some(PhaseTimings {
                discovery_ms: 12,
                file_io_ms: 34,
                parse_ms: 56,
                total_ms: 102,
            }),
            median_error_density_per_1k_loc: Some(4.5),
            slowest_files: vec![SlowestFileEntry {
                path: "slow.pm".to_string(),
                parse_duration_ms: 9,
                line_count: 400,
            }],
            ..test_report(5, 1, 2, 0, BTreeMap::new())
        };

        let json = serde_json::to_string(&report).expect("serialize");
        assert!(json.contains("\"phase_timings\""), "phase_timings key missing");
        assert!(json.contains("\"discovery_ms\":12"), "discovery_ms value missing");
        assert!(
            json.contains("\"median_error_density_per_1k_loc\":4.5"),
            "median density key missing"
        );
        assert!(json.contains("\"slowest_files\""), "slowest_files key missing");

        let back: SweepReport = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.phase_timings, report.phase_timings);
        assert_eq!(back.median_error_density_per_1k_loc, report.median_error_density_per_1k_loc);
        assert_eq!(back.slowest_files, report.slowest_files);
    }

    #[test]
    fn test_sweep_report_old_schema_deserializes_with_none_fields() {
        // schema 1.2.0 JSON (no phase_timings / median / slowest_files)
        // must deserialize cleanly with None / empty defaults.
        let old_json = r#"{
            "schema_version": "1.2.0",
            "commit": "abc",
            "timestamp": "2026-04-09T00:00:00Z",
            "corpus_profile": "system",
            "corpus_roots": ["/usr/share/perl"],
            "resolved_roots_count": 1,
            "perl_version": "5.38",
            "total_files": 10,
            "files_unreadable": 0,
            "clean_files": 10,
            "files_with_errors": 0,
            "total_error_nodes": 0,
            "first_error_buckets": {},
            "elapsed_secs": 1.0
        }"#;
        let report: SweepReport = serde_json::from_str(old_json).expect("deserialize");
        assert!(report.phase_timings.is_none());
        assert!(report.median_error_density_per_1k_loc.is_none());
        assert!(report.slowest_files.is_empty());
    }

    #[test]
    fn test_file_result_old_schema_deserializes_without_new_fields() {
        // Per-file entries predating 1.3.0 lack parse_duration_ms / line_count;
        // those must default to None without a deserialization error.
        let old_json = r#"{
            "path": "Foo.pm",
            "status": "clean",
            "error_node_count": 0
        }"#;
        let result: FileResult = serde_json::from_str(old_json).expect("deserialize");
        assert_eq!(result.path, "Foo.pm");
        assert!(result.parse_duration_ms.is_none());
        assert!(result.line_count.is_none());
    }

    #[test]
    fn test_print_summary_with_phase_timings_does_not_panic() {
        // Smoke test: print_summary must tolerate the new optional fields
        // (populated) without panicking.
        let report = SweepReport {
            phase_timings: Some(PhaseTimings {
                discovery_ms: 5,
                file_io_ms: 10,
                parse_ms: 20,
                total_ms: 40,
            }),
            median_error_density_per_1k_loc: Some(2.5),
            slowest_files: vec![SlowestFileEntry {
                path: "slow.pm".to_string(),
                parse_duration_ms: 15,
                line_count: 250,
            }],
            ..test_report(5, 1, 2, 0, BTreeMap::from([("unclosed_brace".to_string(), 1)]))
        };
        print_summary(&report);
    }

    #[test]
    fn test_print_summary_without_phase_timings_does_not_panic() {
        // Smoke test for the old-schema path: no timings, no density, no
        // slowest list — summary must still render headline counters.
        let report = test_report(5, 1, 2, 0, BTreeMap::new());
        print_summary(&report);
    }
}
